### ISSUE TITLE
Files label

### ISSUE THREAD

**Issue by horus68** [mikespub-org/seblucas-cops#100]
The Files label shouldn't be better named as "Extra Files"?
This would avoid issues as the book files are also files!
![files_extra](https://github.com/user-attachments/assets/94c01203-4a1c-4a5f-92d9-22797c038dc0)

**Comment by mikespub** [comment]
I wanted to keep it short, but if you think it might confuse people I have no problem switching to Extra Files.
Either way, it won't be shown unless there are in fact extra files :-)
