### ISSUE TITLE
Is there/will there be support for KoboSync?

### ISSUE THREAD

**Issue by TomJansen** [mikespub-org/seblucas-cops#109]
Hi,

Thanks for continuing development on this! I was wondering, is there support for KoboSync or do you have maybe plans to support it in the future?

**Comment by mikespub** [comment]
No, I've had a look at how Calibre + plugins or calibre-web deal with it (and the number of issues it generates), and I'm afraid this would be too much to handle - especially for something I'd never use myself, sorry.

Having said that, if you ever feel the itch to develop it, feel free to submit a pull request for it ;-)

As I understand, it would require some big additions to the code base though, especially if you want to support multiple databases, multiple users or devices etc.
