### ISSUE TITLE
Error on Recent addtions setting >40

### ISSUE THREAD

**Issue by jillmess** [mikespub-org/seblucas-cops#118]
With 'recent additions' option at default 50 (or anything >40) I am getting the following:
Error
COPS: Call to undefined function SebLucas\Cops\Language\transliterator_create()
Please report this issue at etc

Setting a custom value to 40 or less is ok but anything higher has the error.

**Comment by mikespub** [comment]
Hi @jillmess - I'm guessing that:
a. some book between # 41-50 has a title with non-ASCII characters, and
b. you do not have the `intl` extension (Internationalization) enabled on your PHP web server?

This is a standard PHP function available once you enable the extension: https://www.php.net/manual/en/transliterator.create.php

You will see the same error when you try to access those books via anywhere else, e.g. by author, etc.

**Comment by jillmess** [comment]
No book with non-ASCII that I can see but I will investigate this further.  I don't (and never did) have intl enabled.  The confusion is that it works without error on 2.8.1 which I still have installed.

**Comment by mikespub** [comment]
The main difference is that with COPS 3.x it generates links that include the title - and those need to be translated if they contain some weird characters...

In the past the `intl` extension was only needed when you enabled the $config['cops_normalized_search'] option.

**Comment by mikespub** [comment]
Apparently you need to install [PHP Extensions](https://www.qnap.com/en/app_releasenotes/list.php?app_choose=PHPExtensions)

**Comment by jillmess** [comment]
Thanks. Sorted by installing PHP Extensions.
