### ISSUE TITLE
"COPS: Class name must be a valid object or a string" when accessing custom column.

### ISSUE THREAD

**Issue by Mossop** [mikespub-org/seblucas-cops#121]
I have a couple of custom columns in my catalog, `read`, `genre`, `collection`. When I try to access these through cops it presents the list of things in the column (e.g. for `read` it lists `No`, `Yes` and `Not Set`) however when I click on one of those the page displays:

```
Error

COPS: Class name must be a valid object or a string

Please report this issue at https://github.com/mikespub-org/seblucas-cops/issues if needed
```

**Comment by Mossop** [comment]
Forgot to mention that I'm running this with the linuxserver docker container.

**Comment by mikespub** [comment]
Thanks for reporting this issue @Mossop - it should be fixed in the next release

**Comment by mikespub** [comment]
See [release 3.4.6](https://github.com/mikespub-org/seblucas-cops/releases/tag/3.4.6)

**Comment by Mossop** [comment]
Works great, thanks for the quick fix!
