### ISSUE TITLE
sqlite not supported on my server

### ISSUE THREAD

**Issue by dKodiak** [mikespub-org/seblucas-cops#122]
any way to get cops to work when i get an splite error?

**Comment by dunxd** [comment]
Install php's sqlite module on your server.

**Comment by mikespub** [comment]
Hi @dKodiak - most PHP installations include the sqlite extension by default as @dunxd mentioned.

In some cases you may need to enable it and/or install additional libraries to make it work. Please check the result of `index.php/check` or `checkconfig.php` for any other missing modules or configuration.
