### ISSUE TITLE
[question] alpine 3.21 rebase for LSIO container

### ISSUE THREAD

**Issue by drizuid** [mikespub-org/seblucas-cops#123]
I didn't see a better way to contact you than this, please let me know if there is one, of if you would like to join our discord as a community dev.  

Anyway, I am looking at rebasing the container to Alpine 3.21. Currently we are using php83 stuff, alpine 3.21 can still do this, but also supports php84.

To give some precise numbers, php83-dom for example, is currently using 8.3.14-r0, we could potentially change to 8.4.1-r0.
below is the list of items that would change
```
    php83-dom
    php83-gd
    php83-intl
    php83-pdo_sqlite 
    php83-sqlite3
```
do you see any  particular issues? obviously we would test before pushing this to latest, but I wanted to involve you in the process.

for now, i will do a simple draft PR to use 3.21 with the php83 stuff, as our alpine-nginx 3.21 test is going to be php83 so php84 may be a moot point. I wont be able to build until we sufficiently test the base image, so there is no rush on response or anything.

**Comment by mikespub** [comment]
Hi @drizuid

I'm not aware of any blocking points for COPS if you want to go from PHP 8.3 to PHP 8.4 for alpine 3.21, but I haven't run any tests with it yet.
Based on the PHP 8.4 upgrade notes, I didn't find any obvious issues except the change in PDO_SQLITE driver with PDO::sqliteCreateFunction() becoming an alias for Pdo\Sqlite::createFunction(), but that should be transparent.

When the base image is ready for PHP 8.4 let me know and I can test it out with COPS before you merge the PR.

Thanks

**Comment by drizuid** [comment]
Thanks! Right now, it sounds like our base wont move to php84, but just in case, ill reach out. Alpine 3.21 has a lot of changes so it'll be a bit before we go live regardless.  Does this location work for me to engage with you or do you have another preference?

**Comment by mikespub** [comment]
hi @drizuid works for me

**Comment by dunxd** [comment]
FYI the version of Alpine that is used in Home Assistant addons still uses PHP 8.3.

I tried forcing 8.4 by specifying php84 etc in the apk add line in Dockerfile but this resulted in failure.  I normally have no version specified in the apk add line, so it will pull in the default version, which currently appeards to be 8.3.  I'll be interested to see when Home Assistant starts using Alpine 3.21 and if this results in PHP 8.4 being used. I suppose I should specify php83 to avoid any surprises.

**Comment by drizuid** [comment]
@mikespub we didn't move to php8.4 in the base, but do you happen to know of anyone that can test since alpine 3.21 had a lot of changes.

`ghcr.io/linuxserver/lspipepr-cops:3.4.6-pkg-852e095d-dev-c33485f181fdd80058fe26bf302b8a295eabffc8-pr-61`
CI looks good for a new install, but we want to ensure an upgrade goes well before merging

**Comment by mikespub** [comment]
Hi @drizuid

I didn't see any issues with smoke tests or unit tests, so it's looking good :-)

For unit tests:
```sh
$ apk add php83-tokenizer  # needed for phpunit in dev mode
$ cd app/www/public
$ composer update -o
$ nano tests/FetchHandlerTest.php  # replace kepubify path with /usr/bin/kepubify
$ vendor/bin/phpunit
...
Tests: 774, Assertions: 2035, Failures: 26, Warnings: 1, Skipped: 1
```
You'll see some failed unit tests for BrowserKit and OpdsRenderer here, but the same tests fail in previous alpine version too, and the rest works as expected.

**Comment by drizuid** [comment]
you're comfortable this will be fine for an in-place upgrade as well? if yes, ill merge here in a few minutes, thanks!

**Comment by mikespub** [comment]
It worked in my case. If upgrade of nginx, PHP, services, permissions etc. are all taken care off in the base image, and the COPS upgrade scripts haven't changed either, then we're good to go.
