### ISSUE TITLE
Sort series-like custom columns in order

### ISSUE THREAD

**Issue by Mossop** [mikespub-org/seblucas-cops#124]
I have a series-like custom column (collection) that can contain all books in a wider collection and their order. But when I view the collection in cops it sorts by title and there is no apparent way to sort by the collection order.

**Comment by mikespub** [comment]
Thanks - it's good to have some specific use cases to improve COPS :-)

The *default* sort order for booklists depends on what you're browsing in, but in general it's by book title (sort field).
This is defined in the `SQL_BOOKLIST` constant for the different Calibre entities (author, serie, publisher, rating, tag, ...) or in specific BookList SQL_* queries.

So for authors it's by series and series_index, for series it's by series_index, for recent books it's by pubdate desc etc.

If you use the `bootstrap2`, `bootstrap5` or `twigged` templates, you can sort these booklists by other book fields (see `$config['cops_html_sort_links']`) via the web interface, but not by custom column fields.

I imagine that for series-like custom columns, it would make sense to sort by the `extra` field by default.
For integer custom columns we could also sort by value (asc or desc) if we split by range, or for date custom columns we could sort by date if we split by year, etc.

**Comment by mikespub** [comment]
Included in [release 3.5.4](https://github.com/mikespub-org/seblucas-cops/releases/tag/3.5.4)

**Comment by Mossop** [comment]
Works wonderfully, thanks!
