### ISSUE TITLE
Cops-php82 and nginx - setup

### ISSUE THREAD

**Issue by ekroko** [mikespub-org/seblucas-cops#128]
Hi, 
I tried to setup cops-php82 (Version 3.4.6) on my openmediavault system Version 7.1 using nginx and php8.2 with its own site.
But I couldn't get it to work.
I'm using the original cops-1.1.3 version together with OMV Version 6 (based on php7) successfully an want to restore this functionality.

First: If I'm using cops-346 together with "php -S 0.0.0.0:9000" - everything works as expected - navigation, download, searching.

But if I'm trying to use nginx as frontend I could not get it to work.
I tried to configure nginx the following way (left out: acess/error log entries)

```server {
listen 90;
root   /var/www/cops;
index index.php;
server_name cops;
    location ~* \.php {
       include /etc/nginx/fastcgi.conf;
       fastcgi_pass unix:/run/php/php8.2-fpm-cops-webgui.sock;
     }
```
I left out the usual "$" at the end of "location"-line - that's the only way to get the main menu.
The local.php contains mainly beside the location of calibre directory
`
$config['cops_front_controller'] = '';
`

With this setup I could successfully search for names, ... in the main menu, but all URLs look like this:
`/index.php/index.php?page=9&search=1&db=&query=dos&_=1734867465314`

or if I click on the "Authors" item
`"GET /index.php/index.php/authors?_=1734867855598`

As you can see, there are always two (or even more) `index.php'`s ath the beginning.

I would assume that I'm doing something wrong with the nginx setup together with cops_front_controller, however I'm running out of ideas now.

Any ideas?
Many thanks in advance, 
Thomas.

**Comment by mikespub** [comment]
COPS 3.x is using route URLs (/index.php/this/that) by default instead of query parameters (/index.php?page=this&id=that), so your nginx config needs to split the path_info before passing it to fastcgi.

You can find an example in the  [default config](https://github.com/linuxserver/docker-cops/blob/master/root/defaults/nginx/site-confs/default.conf.sample) of the [linuxserver/docker-cops](https://github.com/linuxserver/docker-cops) container image, or check out the old [Wiki page](https://github.com/mikespub-org/seblucas-cops/wiki/Full-example-with-Nginx)

**Comment by ekroko** [comment]
Thanks a lot for showing me the correct split_path_info in your documentation. Now there is always only one "index.php" in the URL. 
However when I'm trying to e.g .get the list of authors, series, ... the URL looks ok
`"GET /index.php/authors?_=1734893727303 HTTP/1.1" 200 1998 "http://mymediavault.fritz.box:90/index.php/authors" `
but the result list does not contain any list of books, even if in the result list it says
`"entries -> content	"Alphabetical index of the 6488 authors"" `
Any ideas what I'm still doing wrong?
Many thanks in advance, Thomas

**Comment by mikespub** [comment]
Hi @ekroko

Do you mean that you get the same output for `/index.php/authors` as for `/index.php`, or what do you get back?

Can you see if `/index.php/check` works and gives you the same result as `/checkconfig.php`?

I'm not an expert on nginx + PHP, but it sounds like you didn't add something like
```
include /etc/nginx/fastcgi_params;
```
in your nginx config, so it doesn't set all the necessary variables for PHP (and COPS) to work with...

**Comment by ekroko** [comment]
Hi @mikespub,
yes, I get the same output for `/index.php/authors` as for `/index.php`. Same result for `/index.php/check`.
Again I started from scratch, took the example nginx-file and adjusted the few parameters.
```    location ~ ^(.+\.php)(.*)$ {
       fastcgi_split_path_info ^(.+\.php)(.*)$;
       if (!-f $document_root$fastcgi_script_name) { return 404; }
       fastcgi_pass    unix:/run/php/php8.2-fpm-cops-webgui.sock;
       #fastcgi_pass 127.0.0.1:9000;
       fastcgi_index index.php;
       fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
       include /etc/nginx/fastcgi_params;
    }
```
and did the same with the provided local.php for cops. Results remain the same :-(

Well I think, that I will now switch to the embedded php webserver, because there everything seemed works.

Many thanks for your effort with my struggle 
and especially for your effort providing an up-to-date COPS for php-8!

I will therefore close this issue with "cant't repro" reason.

Thomas.

**Comment by mikespub** [comment]
Thanks @ekroko - I'm sorry to hear you didn't find a working solution with nginx on your openmediavault system. You may want to check if there actually is a file `/etc/nginx/fastcgi_params` and if it contains something like:

```
fastcgi_param  PATH_INFO          $fastcgi_path_info;
```
Otherwise you could add it to the configuration here...

**Comment by ekroko** [comment]
:-) That was the one line which was missing. Now it works even with nginx. :+1:
