### ISSUE TITLE
Some new features in 1.4.x that could use some templating (using bootstrap2 here)

### ISSUE THREAD

**Issue by mikespub** [mikespub-org/seblucas-cops#13]
Some new features in 1.4.x that could use some templating (using bootstrap2 here):

1. Sorting
This one seems OK on small & large screens, but wraps around on medium screens

![cops_sort](https://github.com/mikespub-org/seblucas-cops/assets/1447115/519abf6e-3636-4a00-8ff2-9c374c043dab)

2. Filtering
This one seems OK, but using any other class than navbar-brand for the filter doesn't seem to work - ~~and it probably should be on the right of the Search button, no?~~

![cops_filtered](https://github.com/mikespub-org/seblucas-cops/assets/1447115/b68f9732-fbf9-457b-9a99-c786c9b8a13a)

3. Filter Links
This one seems OK on small screens, but the *page content* isn't nicely grouped on medium & large ones

![cops_filters](https://github.com/mikespub-org/seblucas-cops/assets/1447115/4b31e675-9983-445c-bd8e-8e3ed3eba8e0)

This is what it looks like on large screens - *anyone know any bootstrap 3 to make this look nicer (with panels or anything else)?*

![cops_filters_wide](https://github.com/mikespub-org/seblucas-cops/assets/1447115/31eb430e-c965-4246-b532-49b4a2b6cf37)

_Originally posted by @mikespub in https://github.com/mikespub-org/seblucas-cops/discussions/9#discussioncomment-6668273_

**Comment by dunxd** [comment]
I made a PR to move and style the filter links (2 & 3 above).

The position was best done by placing the filter button within the search bar form, and after the code for the form elements.  Some bootstrap botches here - bootstrap v3 is quite limited with margins etc.

The issue with the sort menu wrapping to an additional row is due to all the options being together in a single list.  I would suggest putting the customize/revert template and about links into a separate list and putting that into the footer.

Annoyingly the way to search items work with narrow views mean the filter button wraps to a new row under the search bar.

**Comment by mikespub** [comment]
Thanks @dunxd I'll give it a go later to see how the search appears for me. And moving some of the links to the footer might be a good idea too, but we don't actually have one in bootstrap2 at the moment.

BTW, I noticed that you removed the "headleft" class again. You're right that it's not used in the bootstrap2 styles, but it's actually referred to in the Customize page when updating the template, so removing it sends you back to undefined page...

**Comment by dunxd** [comment]
Hmm - I hadn't realised that.  It can be put in but forces a left float on the element applied to.

Wouldn't it be better if the template changer just refreshed the customise page, allowing the user to cycle through different templates till they find one they like, rather than returning to the previous page.  Changing the other elements doesn't do this.

```javscript
onchange='updateCookie (this); window.location=$(\".headleft\").attr(\"href\");'
```
to 
```javscript
onchange='updateCookie (this); window.location=window.location;'
```
acheives this.

**Comment by mikespub** [comment]
Cool, we can do that then. I didn't know that setting window.location=window.location; would actually force a refresh - I would have guessed it did nothing at all :-)

**Comment by mikespub** [comment]
Hmmm - sorry, I had a look at how your changes looked, and it doesn't really work for me after all.

For example, you're browsing books from Arthur Conan Doyle, and click on Links to see that he has a couple of books tagged as Short Stories. So you click on that link to drill down, and you get the short stories for that author. Then you can either go back to the author, or continue in short stories, etc. This works better if those Links/Books/Filter icons are right next to the Title - my mistake...

Perhaps you can use something like it in your future bootstrap3 (or whatever you'll call it)?

I'm still interested in how to improve the actual page content on medium/large screens for item 3. above though, if you can find a way

**Comment by dunxd** [comment]
If you want to associate the filter links with the title currently in brand, then the way you were doing it using navbar-brand class is the best way to do it.

What I am thinking of for my template is to have the same navigation elements at the top (e.g. Home | Authors | Series | Tags) on every page, and then have a second level of navigation below that for drilling down based on current selection (e.g. controls relating to filtering | related items | search form), and then controls/links relating to the site in the footer (e.g. Customize | Revert to Default | About).

I think the way you have added the filters and related controls lends itself to this.

I didn't think that `windows.location` was editible either - but changing it works.  `window.location.reload()` should achieve the same thing and the intention is clearer.

Options for controlling the point where the icons wrap onto a second row [are limited](https://getbootstrap.com/docs/3.4/components/#navbar-default) with Bootstrap 3 (and not sure if v4 or 5 are any better). You probably don't want to edit the source of bootstrap/less to change `@grid-float-breakpoint`.  Personally I think putting global controls/links in the footer is the better option.

**Comment by mikespub** [comment]
Thanks, but I'm certainly not going to mess with bootstrap source code - it's hard enough for me to try and use it as it is :-)

About point 3. above I tried to clarify my main issue: it's the *page content* that doesn't look nice on large screens - ideally I'd like to see the content grouped somehow...

**Comment by dunxd** [comment]
Do you want to group the category names with their values, or do you want to organise categories?

First should be relatively easy. Second would need to dispense with the iteration with doT and pull each category from an array.

**Comment by mikespub** [comment]
I'd be happy with some kind of visual break between categories, or perhaps some vertical alignment of items within a category, and a "column" for each category.

| Authors | Languages | ... |
|----------|-------------|---|
|  auth 1  | lang 1 | ... |
|  auth 2  | lang 2 |  |
|  auth 3  |  |  |
|  ...  |  |  |

Does that make sense to you for larger screens, or do you see some other kind of arrangement work better?

At the moment the template recognizes those by the value == "" (as opposed to some number), so you can still loop over all entries and I didn't need to change the data coming from JSON. But I'd be OK to reconsider the data entries if there's no other way...

**Comment by mikespub** [comment]
Outdated
