### ISSUE TITLE
Placement of calibre databases outside cops directory

### ISSUE THREAD

**Issue by marioscube** [mikespub-org/seblucas-cops#19]
If I place my calibre databases inside the cops directory /var/www/html/cops/ (Debian 12/php8.2/apache2) I can access my databases.

If I place the calibre databases inside /home/debian/books of on another disk /mnt/HD1/books I cannot access these databases.
Error on checkconfig.php.

Is this:
a) a php error  (I could do this with php7.4/debian 11)
b) a (new) cops error
c) a combination of both

**Comment by dunxd** [comment]
Did you put a / at the end of the path in your config? That is required.

**Comment by marioscube** [comment]
@dunxd 

I know it’s required.

Yes I put a / there.

**Comment by marioscube** [comment]
@mikespub @dunxd 

Webserver logs:
cat access.log 
192.168.1.107 - - [15/Aug/2023:21:16:09 +0200] "GET /cops/ HTTP/1.1" 302 239 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:109.0) Gecko/20100101 Firefox/115.0"
192.168.1.107 - - [15/Aug/2023:21:16:09 +0200] "GET /cops/checkconfig.php?err=1 HTTP/1.1" 200 1342 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:109.0) Gecko/20100101 Firefox/115.0"


cat error.log 
[Tue Aug 15 21:15:58.260675 2023] [mpm_prefork:notice] [pid 815] AH00163: Apache/2.4.57 (Debian) configured -- resuming normal operations
[Tue Aug 15 21:15:58.260709 2023] [core:notice] [pid 815] AH00094: Command line: '/usr/sbin/apache2'
[Tue Aug 15 21:16:09.744077 2023] [php:error] [pid 1005] [client 192.168.1.107:61542] PHP Fatal error:  Uncaught Exception: Database <2> not found. in /var/www/html/cops/lib/Calibre/Database.php:164\nStack trace:\n#0 /var/www/html/cops/lib/Calibre/Database.php(191): SebLucas\\Cops\\Calibre\\Database::error()\n#1 /var/www/html/cops/lib/Calibre/Database.php(206): SebLucas\\Cops\\Calibre\\Database::getDb()\n#2 /var/www/html/cops/index.php(44): SebLucas\\Cops\\Calibre\\Database::checkDatabaseAvailability()\n#3 {main}\n  thrown in /var/www/html/cops/lib/Calibre/Database.php on line 164

config_local.php
    $config['calibre_directory'] = array (      "COPStest"      =>      "./Books/COPStest/",
                                                "CalibreFree"   =>      "./Books/calibrefree/",
                                          //    "CalibreFree2"  =>      "/home/debian/Books/calibrefree/",
                                                "CalibreFree3"  =>      "/mnt/books/calibrefree/",
                                         );

First 2 lines work, 4th (and 3rd) does not.

/mnt/books/calibrefree is 777

So it looks like an open_basedir issue. Is that on debian bookworm with php 8.2?

**Comment by mikespub** [comment]
@marioscube I forgot one trick that might help you find out where to look further, if you have terminal access to the server.

If you installed cops in /home/whatever/cops and you don't use port 8080 on the server, you can start the PHP built-in web server with:

```
$ php -S 0.0.0.0:8080 -t /home/whatever/cops
```

Then if you browse to http://...:8080/ with the hostname or ip of your server, you should see the COPS homepage without going through your default web server. If that works, the code & library are fine, but the web server and/or access rights are not OK.

And if your current user can't access that library either, it will show on the terminal as an error as well:

```
PHP Fatal error:  Uncaught Exception: Database <> not found. in /home/whatever/cops/lib/Calibre/Datatabase.php
```
But then you have a bigger issue since you can't access your own library now :-)

**Comment by marioscube** [comment]
@mikespub @dunxd 
started:
**php -S 0.0.0.0:8080 -t /var/www/html/cops**

**http://<IP>:8080/cops**

**Output in SSH terminal**
[Tue Aug 15 22:43:30 2023] PHP 8.2.7 Development Server (http://0.0.0.0:8080) started
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61668 Accepted
[Tue Aug 15 22:44:00 2023] PHP Fatal error:  Uncaught Exception: Database <2> not found. in /var/www/html/cops/lib/Calibre/Database.php:164
Stack trace:
#0 /var/www/html/cops/lib/Calibre/Database.php(191): SebLucas\Cops\Calibre\Database::error()
#1 /var/www/html/cops/lib/Calibre/Database.php(206): SebLucas\Cops\Calibre\Database::getDb()
#2 /var/www/html/cops/index.php(44): SebLucas\Cops\Calibre\Database::checkDatabaseAvailability()
#3 {main}
  thrown in /var/www/html/cops/lib/Calibre/Database.php on line 164
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61668 [302]: GET /cops/ - Uncaught Exception: Database <2> not found. in /var/www/html/cops/lib/Calibre/Database.php:164
Stack trace:
#0 /var/www/html/cops/lib/Calibre/Database.php(191): SebLucas\Cops\Calibre\Database::error()
#1 /var/www/html/cops/lib/Calibre/Database.php(206): SebLucas\Cops\Calibre\Database::getDb()
#2 /var/www/html/cops/index.php(44): SebLucas\Cops\Calibre\Database::checkDatabaseAvailability()
#3 {main}
  thrown in /var/www/html/cops/lib/Calibre/Database.php on line 164
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61668 Closing
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61669 Accepted
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61669 [404]: GET /cops/checkconfig.php?err=1 - No such file or directory
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61669 Closing
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61670 Accepted
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61670 [200]: GET /favicon.ico
[Tue Aug 15 22:44:00 2023] 192.168.1.107:61670 Closing

Same error. It's PHP!

**Comment by marioscube** [comment]
@mikespub @dunxd 

**OK!** partly my mistake, I made a combination of typo and permission error.
It now works for calibre libraries on other disks /mnt/HD1 .

However it still does not work on /home/debian. As far as I can see no typo's and permissions are ok!

I will try with other directories (maybe a typo I'm blind to).

**Comment by marioscube** [comment]
@mikespub @dunxd 

After some quick testing my conclusions:

I can **NOT** place the Calibre library inside /home/debian/ any other place is fine, but **NOT** /home/debian/.

I suppose that is safe, but on a home server not convenient.
I like my sh*t in /home/USER and keep the rest of the system as clean as possible. My personal stuff is on other machines.

Don't like it, but I can live with it. (I will test some more tomorrow.) 

Happy it's not a COPS issue! Keep up the good work!!

**Comment by mikespub** [comment]
Thanks for trying it & figuring out what the limitations are - very good to know. Have fun with it as always :-)
