### ISSUE TITLE
epub-loader missing from 1.4.3 zip

### ISSUE THREAD

**Issue by dunxd** [mikespub-org/seblucas-cops#23]
When incorporating 1.4.3 into HA-COPS from the zip file, I noticed that the epub-loader folder is missing from /resources - this stops the epub reader from working.  I copied that folder from the source, and things are working, but you might want to fix it in the release.

**Comment by mikespub** [comment]
Ouch - thanks, good catch. When I switched to ZipFile instead of clsTbsZip as default class for EPub(), I forgot to change the build.xml file accordingly :-(

**Comment by mikespub** [comment]
Replaced release file cops-1.4.3.zip with cops-1.4.3b.zip - thanks
