### ISSUE TITLE
Filter names translations

### ISSUE THREAD

**Issue by dunxd** [mikespub-org/seblucas-cops#24]
On a page that shows filters, and the filter is series, that filter is labelled "Serie".  

I am guessing this is just outputting the name of the class, as I can't find it in the translation files.  Is that right? If so then none of the filter names get translated, and all are in English apart from Serie?

**Comment by mikespub** [comment]
Hmm - sorry yes, that was still on my todo list. I've been trying to match everything I used to existing translation keys and minimize the number of new strings that would need a translation everywhere, but I skipped that for the classes - guess we'll have to add a few missing ones too...

**Comment by mikespub** [comment]
There we go... Note: they're all in plural form, since we don't have the singular form available in most cases

**Comment by mikespub** [comment]
Included in [release 1.4.4](https://github.com/mikespub-org/seblucas-cops/releases/tag/1.4.4)
