### ISSUE TITLE
Ignored categories inaccessible to templates?

### ISSUE THREAD

**Issue by dunxd** [mikespub-org/seblucas-cops#30]
For the sake of completion, I was going to hide ignored categories from the navmenu of _bootstrap5_ template, but ignored categories do not appear to be available to templates through Javascript.  Perhaps they belong in `it.c.config`?

Note that if they were to be added, it would need to be based on the global config setting _and_ the customization setting from the `ignored_categories` cookie. And since the client and server side templating engines handle methods on objects differently, it might require a separate variable for each category.  For example to allow a template like this:

```
{{? ignore_authors != 1}}
  <li class="nav-item">
    <a class="nav-link{{? it.page == 1}} active{{?}}" href="index.php?page=1"{{? it.page == 1 }} aria-current="page"{{?}}>{{=it.c.i18n.authorsTitle}}</a>
  </li>
{{?}}
```
I don't think it would be possible to use a regex to check for the presence of "authors" in a single ignored_categories variable - Javascript would use `ignored_categories.indexOf("author")` and PHP would use `strContains($ignored_categories, "author")`.

I'm also open to not being completist and leaving the top level navigation hard coded in the template!

**Comment by mikespub** [comment]
Actually it's not that difficult to check for the presence of a value in an array, if you flip the keys & values in PHP first.

With the commit above you can use something like this in your templates:

```
{{? it.sortoptions.rating && !it.c.config.ignored_categories.rating }}
...
{{?}}
```

This will also take into account anything you might have set via cookies, even if you change it on the fly - at least once you click on the COPS link to get a complete reload of the page and get the latest it.c.config.* values...

**Comment by dunxd** [comment]
That's great! Thanks.

**Comment by mikespub** [comment]
No problem. The main reason I pass along $request all over the place now (other than getting rid of global vars), is exactly so that we can send info that depends on config, cookie, params, ... - it would be a shame not to take advantage of it :-)
