### ISSUE TITLE
util.js overrides page title setting in template

### ISSUE THREAD

**Issue by dunxd** [mikespub-org/seblucas-cops#31]
Line 323 of util.js forces the page title to be the same as data.title, even if this has been defined in the template file.html.

https://github.com/mikespub-org/seblucas-cops/blob/ec3f8d00efe4c418f8305c272c3f3ca486d82c68/util.js#L323

I have tried commenting out the line in util.js, but this isn't working.  I think that the file.html template is used before some javascript variables are populated (e.g. `it.libraryName`). What I would like to do is:

```html
<title>{{=it.libraryName}} > {{=it.title}}</title>
```
Currently I only seem to be able to do this by hardcoding into util.js:

```javascript
document.title = data.libraryName + " > " + data.title;
```

**Comment by mikespub** [comment]
file.html is only used once and always server-side, at the initial page load in index.php. After that, if you use client-side rendering it's never used again. You go directly to getJSON.php to get the values, and load the other templates via Javascript.

That initial it.title for file.html comes from Config::get('title_default') and it's set in index.php. And yes, the same config is used to set it.libraryName in JSON render for use in other templates afterwards :-)

I don't really have a problem changing util.js to use that as a title prefix if that's what you have in mind?

**Comment by dunxd** [comment]
Ah ok - could do with a comment in `file.html` to clarify this - otherwise the natural assumption is it works exactly the same as the other template files.

Since util.js is where the page title is ultimately set (there is 1-2 seconds where the title set in file.html is visible before being replaced) it doesn't really matter what file.html says - "COPS loading..." might be better, and clearer to template builders.

Since people use lots of tabs these days having that text clear is useful for finding a specific tab. 

Having the page title set in util.js is ok, but it's a global change, not a template so worth getting right.

In my opinion {{Library Name}} | {{Page Name}} is sufficient - e.g. COPS | Recent Additions.

**Comment by mikespub** [comment]
OK, I'll check what we use to modify the title for multiple database setup and do the same here

**Comment by mikespub** [comment]
Hmmm, it seems doT-php doesn't allow you to specify the param to use in a defined template `{{#def.template:param}}` like doT.js does, so I guess my idea to replace (or include) file.html with a full page index.html for doT will have to wait a bit longer :-(

In the meantime the document title should be updated both for client-side and server-side rendering, so I'm closing this one...
