### ISSUE TITLE
Translation updates

### ISSUE THREAD

**Issue by horus68** [mikespub-org/seblucas-cops#39]
16 new language strings are available to be translated online using Transifex here:
https://app.transifex.com/aletris/cops/
Please join in to translate!

Those strings are from version 2.0.1 (Cops Mikespub's fork)
PR with new translations will be created in a few days (depending on translators' activity!)

**Comment by mikespub** [comment]
Thanks for organizing this @horus68 - I've tried to limit the number of new strings to be translated, but some inevitably pop up when we want to describe new features in the interface

**Comment by horus68** [comment]
included new strings from #47

**Comment by mikespub** [comment]
Thanks again @horus68 - any idea when you might have some updated language files as PR?
