### ISSUE TITLE
Downloading all books by series or author - testers needed

### ISSUE THREAD

**Issue by mikespub** [mikespub-org/seblucas-cops#40]
There's a new feature available to download all books by series or author for a particular format. I'd appreciate if some of you could try it out and see how it works in different circumstances...

At the moment it's only available from source code for the "bootstrap2" and "twigged" templates, but it will be included in the next release.
To activate, there are 2 new config options available - see [CHANGELOG.md](/mikespub-org/seblucas-cops/blob/main/CHANGELOG.md) for details.

@dunxd I'm counting on you to find the right place to put this in the "bootstrap5" template :-)

The template changes are pretty simple:

https://github.com/mikespub-org/seblucas-cops/blob/25eaba2969757f9c89a661abc8934e53fc444c39/templates/bootstrap2/header.html#L15-L21

Thanks

**Comment by dunxd** [comment]
I don't fully understand this.  

Would I see these buttons on any page that lists books - e.g. the recent additions page?  Or only on pages where I have selected an author, or a series, or a tag?  What needs to happen for `it.download` to be true?

What happens if only some of the books have been converted into a particular format? e.g. middle book of a series is only available as AZW but the others are in AZW and EPUB? What does the EPUB button download?

How do the books get downloaded? As a ZIP, or multiple downloaded files?

**Comment by mikespub** [comment]
Sorry, I guess my explanation wasn't too clear. You get a download link per format (configurable) when you browse by series or by author.

For that you need to set:
```
$config['cops_download_series'] = ['EPUB'];
$config['cops_download_author'] = ['EPUB', 'AZW'];
```

The link will give you a .zip file with all the books of that series or author for that format. So the AZW will not be included in the EPUB .zip and vice-versa.

I was thinking that you might have several formats for one book, and you'd only want to download one format - but I guess I could add a '*' format to signify any format or something...

**Comment by mikespub** [comment]
And from your question I gather you'd be more interested in being able to download all books on any particular page, regardless of how you got there?

The grouping by series or author seemed like the most logical place to start, but maybe you have a different view - that's the whole purpose :-)

**Comment by dunxd** [comment]
Series and author makes sense. Tag maybe but could result in large zip files (e.g. if tag is fiction). I don't know if that is an issue.

My question on different version availability is that if I have a series of 3 books, but one of the books is missing a format, say MOBI. Does the button to download all EPUB just download the two EPUB files? The button purports to download all books in a format - but obviously cannot always. That's potentially confusing, especially if the user isn't someone that maintains the Calibre library. If downloading the books from the list page one by one it is obvious if a format is missing (if all the formats are visible on the list page).

Perhaps presenting the download all buttons at the bottom of the list makes this clearer. Or have some brief text accompanying the buttons that makes this clear.

**Comment by mikespub** [comment]
OK, that makes sense. I've added support to download all books for any page, and to download any available format (in the prefered_format order).

```
/*
 * Allow downloading all books shown on a page for a specific format
 * Example: $config['cops_download_page'] = ['EPUB'];
 *
 * To get any format in prefered_format order you can use : ["ANY"];
 * Example: $config['cops_download_page'] = ['ANY'];
 */
$config['cops_download_page'] = [];
```

Does that work out better? Of course you can still tweak how you want to use this for your COPS catalogs, e.g. if you show a large # of books by default on each page in your config (max_item_per_page), you might only activate by series or author, but otherwise using by page and ANY seems to work out fine...

**Comment by dunxd** [comment]
Ok - I spotted a reason why I was getting confused.  In bootstrap5, the title at the top left is the library title - it never changes.  

In bootstrap2 it shows the current context (e.g. Series > Series name).

Without the context, the download button is harder to understand. I am thinking that I will add the context below the main nav-bar - where the sort items currently are. So the top menu is for identifying the site, and quick navigation, and the second menu identifies the current context, and controls relating to that. That means always showing the context, so I need to figure out how I am to do that. Too late to start on it tonight, but I'll probably figure it out tomorrow.

**Comment by mikespub** [comment]
No worries. And you could show the context only when the download option is available, if always showing it would mess up the default display

**Comment by dunxd** [comment]
See PR #42 which I think lays the ground for implementing this in Bootstrap5 - only small changes but I think they make a difference to the usability of the template already.

**Comment by dunxd** [comment]
I noticed that `it.download` is created as an empty array in JavaScript even if `$config['cops_download_page']` is not set in config_local.php. This means that a check for `it.download` will always return true.  In javascript I could just check for `it.download.length > 1` but this won't work server side right?

Incidently, being able to check for download.length > 1 would be useful, since it could be used to prevent the download all buttons showing up on pages with only one book.

**Comment by dunxd** [comment]
Scratch that last bit - it is necssary to check for `it.entries.length > 1` for only one books.  `it.downloads.length` is the number of formats to create zips for.

**Comment by mikespub** [comment]
Hmmm - I was under the impression that an empty array would also be considered "falsy" in Javascript, the same as in PHP. Turns out I was wrong, sorry :-(

However, checking if it.download == [] should work in both cases, no?

**Comment by dunxd** [comment]
`it.download == []` evaluates as false whether the array is empty or not.
Same with `it.download === []`. I can't find a way to assess if a javascript array/object is empty without resorting to a method - which might be because there are several ways to do it with methods.  Google job interview level challenge?

**Comment by dunxd** [comment]
Ok - I got hired.

`it.download[0]`

**Comment by dunxd** [comment]
Which unfortunately chokes server side rendering :-(

**Comment by mikespub** [comment]
Hehe - nice one. But you may hold off on that job interview though, because regardless of whether it.download is true or false in an if () block - which seems to be debatable apparently - when you start looping over it you still won't get a button for an empty array, right?

**Comment by mikespub** [comment]
All this Javascript mess with an empty array being both truthy and falsy depending on the context is making my head hurt.

Let me solve this like I did for filters: if it's empty, it will be set to false in JSON renderer - end of story...

**Comment by mikespub** [comment]
Resolved for now - open new issue if needed
