### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dunxd** [mikespub-org/seblucas-cops#68]
@mikespub is there anything outstanding to resolve before releasing a 2.16 version?

**Comment by mikespub** [comment]
I updated dependencies and was hoping to include the OPDS 2.0 pagination from kiwilan for the next 2.2.x release, but since it's not ready yet I can prepare an intermediate if you want

**Comment by mikespub** [comment]
See [release 2.2.1](https://github.com/mikespub-org/seblucas-cops/releases/tag/2.2.1)

**Comment by dunxd** [comment]
Thanks for doing this release.  I have used it to upgrade HA-COPS - it is working quite nicely in that so far although I found some issues where pihole has started to block jsdelvr.com which I was using to include bootstrap's files.  I might need to include the code in the template so it can be linked to locally and avoid this sort of issue.  In the meantime I have documented this issue with HA-COPS.
