### ISSUE TITLE
Error sending or reading book from additional dbs

### ISSUE THREAD

**Issue by malkavi** [mikespub-org/seblucas-cops#72]
Hi, 
I'm trying to send books from others dbs differents to 0 and I can't. Reading a little bit the code I see that epubreader.php only read data param from url and not the db param needed for identify the correct db. If I try to send a book from db different to 0 I received a book from db=0.
URL example: https://copsurl/epubreader.php?data=7852&db=2

Code used to read the book (EPubReader.php). The db param is readed from the book data not from a param.
```
  public static function getReader($idData, $request)
    {
        $book = Book::getBookByDataId($idData);
        $params = ['data' => $idData, 'db' => $book->getDatabaseId()];
```
Sorry If I am not enough clear or I am missing information.

Thanks for the hard work!

**Comment by mikespub** [comment]
You're absolutely right - I did miss sending the right database information when I split off the EpubReader and Mail classes. Fixed in the latest release
