### ISSUE TITLE
Do you want to be a Translator/Proofreader?

### ISSUE THREAD

**Issue by horus68** [mikespub-org/seblucas-cops#86]
To translate COPS we are now using the Gitlocalize platform:
[![gitlocalized ](https://gitlocalize.com/repo/9640/whole_project/badge.svg)](https://gitlocalize.com/repo/9640?utm_source=badge)
https://gitlocalize.com/repo/9640
![cops_gitlocalize_00](https://github.com/mikespub-org/seblucas-cops/assets/3055443/93e6923a-18f0-4b60-b759-4c87aa867ec9)

**Translators:** 
To translate you just need to login here with your GITHUB account:
https://gitlocalize.com/repo/9640

![cops_gitlocalize_01](https://github.com/mikespub-org/seblucas-cops/assets/3055443/8d4a21fa-bb89-4347-9d5f-39125a66d70d)

**Proofreaders**
We are also looking for language proofreaders, just ask here using your GITHUB user and the language you want to proofread.

**See wiki for details:**
https://github.com/mikespub-org/seblucas-cops/wiki/Update-translations

Note: Transifex platform or Github direct merge will not be used anymore.

**Comment by horus68** [comment]
@burghy86 added to Italian

**Comment by marioscube** [comment]
I used to translate COPS in tranifex in the past.

Just updated the Dutch file for the new COPS.

**Comment by horus68** [comment]
Added:
Dutch @marioscube 
Romanian @HaoSs07
Polish @tntturtl
