### ISSUE TITLE
Support for KFX file download

### ISSUE THREAD

**Issue by christianpayeur** [mikespub-org/seblucas-cops#93]
Currently it is not possible to download KFX files from COPS. Entries in the Calibre database with only KFX files appear in the COPS interface but do not have a download button; only EPUB or AZW3 files are available for download from the GUI.

Would it be possible to add KFX to the list of downloadable formats?

Many thanks!

**Comment by dunxd** [comment]
Take a look at [the entry for `$config['cops_preferred_format']` in `config_default.php` ](https://github.com/mikespub-org/seblucas-cops/blob/ddf3e8975dea91a51ba63c059568f2c45fb8ec1c/config_default.php#L143)

You should override this by creating a line in `config_local.php` that includes `KFX`.  Note that only the first two formats that you specify will be displayed for download next to book entries in a list, but any of them will be included when you click through to the book detail page.  If you often want the KFX version make this one of the first two items in the list.

Does that fix it for you?

**Comment by christianpayeur** [comment]
Yes that did the trick. Many thanks!
