### ISSUE TITLE
Error COPS: SQLSTATE[HY000]: General error: 5 database is locked

### ISSUE THREAD

**Issue by vmbajop** [mikespub-org/seblucas-cops#94]
Connecting to  http://292.268.1.45:8000/ I receive the following error:

```html
Error
COPS: SQLSTATE[HY000]: General error: 5 database is locked

Please report this issue at https://github.com/mikespub-org/seblucas-cops/issues if needed

Link: [Home](http://192.168.0.45:8000/index.php?page=index&db=0&vl=0)
```

I'm using it in Home Assistant, and In my config, I have the following setup:
In HOASS Storage, I have a link to a disk locally configured as NFS. The name is "Biblioteca", and it's accessible in media/Biblioteca.
With HA COPS, I have entered "Biblioteca" in the Library Folder field.
My YAML configuration is:

```yaml
title: Biblioteca Local
library_folder: Biblioteca
rsync: false
reader: monocle
```

Has anyone else had the same problem?

**Comment by dunxd** [comment]
I'll take this one in the HA COPS issues.

**Comment by dunxd** [comment]
It seems related to mounting NFS in Home Assistant, rather than a COPS issue. Mounting via SMB seems to have resolved it.

**Comment by vmbajop** [comment]
Yes, it's right: with SMB resolved it. Thanks so much

**Comment by mikespub** [comment]
Thanks for the help @dunxd :-)
