### ISSUE TITLE
CSS (?) issue on version 2 of seblucas-cops

### ISSUE THREAD

**Issue by marioscube** [mikespub-org/seblucas-cops#95]
I did a fresh install of COPS 2.7.1.

To test I searched for something.

Technically it seems to work, however I think there is a CSS (?) problem.

![Screenshot 2024-08-01 at 17 12 50](https://github.com/user-attachments/assets/dc68a105-76ff-4be0-a1de-da32ed0b9a03)

It should look like this (from older/original version 1.2 of COPS):

![Screenshot 2024-08-01 at 17 13 49](https://github.com/user-attachments/assets/1366caf1-4e74-4942-8cb2-787f1b9486e0)

Any idea how to fix this?

**Comment by dunxd** [comment]
This only seems an issue with the "default" theme. "bootstrap2", "bootstrap5" and "twigged" don't have this issue.

I suspect that the CSS selector for the search suggestions box is not being applied - maybe the id, class or something else changed.

**Comment by marioscube** [comment]
@dunxd 
1 - indeed, only the default them. I forgot to mention that. My bad.
2 - I compared all HTML file and CSS files. To my untrained eye nothing obvious stood out as the cause of this.

I hope someone with a more trained eye can take a look at this.

**Comment by dunxd** [comment]
The other themes pick up their background colour for the dropdown box via the class `tt-menu` which is in the `typeahead.css` file in the other templates' `styles` folder.

I've made a PR (#96) that includes the typescript.css file and calls it from the default file.html template, but haven't had a chance to test it properly.

**Comment by marioscube** [comment]
@dunxd 

Thank you! It looks like your quick fix seems to work. 
This makes the search feature in the default template usable again.

Compared to the original layout it looks horrible though. But that's not your fault. 

I am probably the last default template user alive.
I does not look flashy It's very utilitarian, and that's what I Iike..

**Comment by dunxd** [comment]
After looking at it again, I don't think PR #96 is quite the right fix.  The other templates using the typeahead.css override the styling for the elements with class name prefixed `tt-` in a `style` element within `file.html`, which apply the background, alignment, header bold font etc.  This should probably also be the setting for default. 

However since default template is meant to be utilitarian/backwards compatible perhaps it shouldn't have a suggestions box at all - keep it simple and just present the search results after clicking the search button.

I use the default template with the kindle style applied when browsing my library on my Kindle paperwhite. It works the best with that particular interface.

**Comment by marioscube** [comment]
@dunxd 
If I just copy the relevant parts of typeahead.css to style.base.css I have the dropdown menu functionally working. No need to change file.html and reference typeahead.css.

The bootstrap template also misses the code from typeahead.css, but the other templates look nicer anyway ;-)

I still like the original search results from the old (< version 2) COPS.

![Screenshot 2024-08-04 at 23 27 22](https://github.com/user-attachments/assets/b93bbc6c-11f4-4432-8562-909b45fa1704)

**Comment by mikespub** [comment]
PR included in [release 2.7.3](https://github.com/mikespub-org/seblucas-cops/releases/tag/2.7.3)

**Comment by marioscube** [comment]
Thank you.

The same PR needs to be applied to the original bootstrap theme.

**Comment by mikespub** [comment]
Something that fit me perfectly: https://thecodinglove.com/when-i-try-to-modify-a-css-stylesheet

**Comment by marioscube** [comment]
:-)
