### ISSUE TITLE
Support Data files directory

### ISSUE THREAD

**Issue by russell-phillips** [mikespub-org/seblucas-cops#97]
A lot of my books have [data files](https://manual.calibre-ebook.com/metadata.html#data-files). Would it be possible to get access to the data files via the web interface in some way?

I'm thinking something like a pop-up that would allow me to download individual files, or a button/link that would download the whole data directory as a zip file.

**Comment by mikespub** [comment]
Implementation notes for backend (reference):
https://www.mobileread.com/forums/showthread.php?t=354242
https://github.com/kovidgoyal/calibre/blob/d851c81b8c4acae6e70a15526822050f60d3b6b0/src/calibre/db/cache.py#L3359
https://github.com/kovidgoyal/calibre/blob/d851c81b8c4acae6e70a15526822050f60d3b6b0/src/calibre/db/backend.py#L2017

**Comment by russell-phillips** [comment]
@mikespub I mostly use data files with my gaming books. The data files are usually supplementary PDFs, although there can be a variety of other types too (zip are probably the second most common, with occasional image files, .odt files...)

Mostly I want to be able to download them to whatever device I'm using COPS on. I don't really mind whether that's all the files in a zip, or one at a time.

**Comment by mikespub** [comment]
Included in [release 2.7.5](https://github.com/mikespub-org/seblucas-cops/releases/tag/2.7.5)

For any fancy templating with popup's etc. feel free to submit a pull request ;-)

![image](https://github.com/user-attachments/assets/8ad5dc17-f846-4c8c-ad6d-40f267d99876)

**Comment by russell-phillips** [comment]
I've updated my COPS, and it's working brilliantly, thank you :)
